### ISSUE TITLE
add README.md file

### ISSUE THREAD

**Issue by mcrapet** [mirabilos/git-find#1]
Hi,

This tool is useful. A minimum readme file would be appreciated.

For example:
`set -o pipefail` requires *MirBSD KSH Shell* (mksh) version **R46** or better (I had issue using an old Ubuntu 12.10).

Regards,
Matthieu

**Comment by mirabilos** [comment]
I deliberately did not add any extra file so that the git developers can just merge this repository with history and all.

I guess 12.10 is no longer an issue? Otherwise it’s easily built; I also have a PPA with backports but only for LTS releases.
